version: "3"

services:

  mysql:
    ports:
      - "3306:3306"
    image: mysql:latest
    container_name: mysql_lbd
    environment:
      MYSQL_USER: lbduser 
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lbd_default_bd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_lbd_mysql
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8183:80"